### ISSUE TITLE
Set response timeout

### ISSUE THREAD

**Issue by marianoarga** [kghandour/Ollama-SwiftUI#24]
In local development cases Ollama could take several minutes to respond, it would be nice to adjust the timeout. Thx

**Comment by kghandour** [comment]
Thank you for your suggestion! Will try to implement it soon

**Comment by kghandour** [comment]
Option added in #28 . Will be available with in 1.1.1

**Comment by kghandour** [comment]
Version 1.1.1 has been released https://github.com/kghandour/Ollama-SwiftUI/releases/tag/v1.1.1
You can modify the request timeout in the app preferences where you can update the IP / Port.
