### ISSUE TITLE
Lower Minimum MacOS Version?

### ISSUE THREAD

**Issue by chigkim** [kghandour/Ollama-SwiftUI#30]
Can we have the app to run on earlier MacOS version? Ollama even runs on macOS 11 Big Sur.

**Comment by kghandour** [comment]
Thank you for your suggestion. I will investigate the possibility of that. The only limitation I can see is if Ollama-SwiftUI is using any MacOS 14+ exclusive Swift methods. 
I will try to reply again with my findings.

**Comment by borays** [comment]
My MBA version is 13.6.3, and it prompts that it cannot be used. Is the software version limited to 14+?

**Comment by fearlipe** [comment]
This won't be possible due to Swift methods. 
![Screenshot 2024-05-10 at 12 38 12](https://github.com/kghandour/Ollama-SwiftUI/assets/21061728/1bf61707-159a-4565-a4b9-ad80d0aab223)

**Comment by kghandour** [comment]
Closing this issue. Thanks @fearlipe for your investigation.
