### ISSUE TITLE
Input field loses focus when LLM responds

### ISSUE THREAD

**Issue by BTGUK** [kghandour/Ollama-SwiftUI#31]
**Describe the bug**
During an interaction with a model. the input field at the bottom loses focus when the model outputs a response. As a result, the user has to activate (click on) the input field before a new request can be entered. This makes interactive discussions difficult/cumbersome. 

**To Reproduce**
1. Setup Ollama and Ollama Swift UI and load a model (which one doesn't matter)
2. Click on the input field
3. Type a request in the input field, for example "what are you?" (the actual request doesn't matter)
4. The model response is shown in the chat frame
5. Type a new request, for example "what is your name?" (the actual request doesn't matter)

**Expected behavior**
The input is accepted and the model responds. 

**Actual behavior**
The input is ignored as the focus is now on the chat window. The user has to click (activate) the input field first before they can enter a new request. 

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.3
 - System: Mac Studio M1 Max
 - Ollama Version: 0.1.2.0
 - Ollama Swift UI Version: 1.1.1

**Comment by kghandour** [comment]
Thanks for reporting that behavior. I will look into it. :)
