### ISSUE TITLE
Scrolls to latest prompt automatically

### ISSUE THREAD

**Issue by nonnapopoa** [kghandour/Ollama-SwiftUI#32]
Currently the app does not scroll automatically to the new response I have to manually scroll to latest prompt. It would be great if the app scroll automatically to latest prompt.

![2024-01-30 at 17 35 41](https://github.com/kghandour/Ollama-SwiftUI/assets/150189680/639244de-1bb6-4403-8846-8b4daba15016)

**Comment by kghandour** [comment]
I will look into that behavior. Thanks for reporting it :)
