### ISSUE TITLE
Sorry, I feel very stupid, but how to run the project? I can't see the app or xproject file?

### ISSUE THREAD

**Issue by arthrod** [kghandour/Ollama-SwiftUI#34]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kghandour** [comment]
Hello @arthrod, you can simply download the application from the releases on the side of the page. You don't need to build it yourself.
