### ISSUE TITLE
Submit Prompt with Enter instead of clicking the send button

### ISSUE THREAD

**Issue by brasfb** [kghandour/Ollama-SwiftUI#42]
**Is your feature request related to a problem? Please describe.**

I'm used to typing a prompt and hitting "Enter" or "Command + Enter" to submit, but thus far I don't get any response when this happens. Instead, I have to use the old mouse to do the trick. Am I doing something wrong or is this just not built into the 

**Describe the solution you'd like**
I want to be able to type a prompt, hit enter, and get a response rather than using the mouse or trackpad.

**Describe alternatives you've considered**
I'm a little new to Swift programming, TBH I have no clue where to start.

**Additional context**

https://github.com/kghandour/Ollama-SwiftUI/assets/120994691/5825ca76-394c-460b-ba4a-e475a2dd7b9d

**Comment by kghandour** [comment]
You are not doing anything wrong. That interaction existed in old versions, however, they lacked multi line support. With the addition of multiline, this feature went missing. I can try to add command + enter to quickly send the prompt instead of using the mouse.

**Comment by devasworski** [comment]
command + enter would be a great solution!

**Comment by zajerao** [comment]
be nice to have indeed.

**Comment by kghandour** [comment]
Thank you for the suggestions!

New release ( 2.0.1 ) added support for command + enter to send a message, and command + r to refresh connection to server.
